#!/bin/bash

###
### Main Executor
###
### Script that validates software dependencies and call VRE_RUNNER.py
###


DEPENDENCIES=(
	"cwltool"\
	"singularity"\
)
PROGNAME="VRE_RUNNER.py"

# Validate dependencies

REALPATH="$(realpath "$0")"
BASEDIR="$(dirname "$REALPATH")"

case "$BASEDIR" in
/*)
  true
  ;;
*)
  BASEDIR="${PWD}/$BASEDIR"
  ;;
esac

for prog in "${DEPENDENCIES[@]}" ; do
  type -a "$prog" >/dev/null
  if [ $? -ne 0 ]; then
    echo "UNCONFIGURED: No $prog executable found" 1>&2
    exit 1
  fi
done

# Run VRE_RUNNER

source "$BASEDIR"/venv/bin/activate
# Create a nodejs running from within the environment
if [ ! -x "$BASEDIR"/venv/bin/nodejs ] ; then
    cp -p "$BASEDIR"/nodejs_singularity_wrapper.bash "$BASEDIR"/venv/bin/nodejs
    chmod +x "$BASEDIR"/venv/bin/nodejs
fi
if [ ! -x "$BASEDIR"/venv/bin/node ] ; then
	ln -s nodejs "$BASEDIR"/venv/bin/node
fi
exec python -u "${BASEDIR}"/"${PROGNAME}" "$@"
exit 1
